#include "engine/AudioSystem.hpp"

#include "miniaudio.h"

#include <algorithm>
#include <array>
#include <iostream>
#include <string_view>
#include <vector>

namespace sokoban {
namespace {

constexpr std::array<const char*, 5> footstepFileNames {
    "footstep_concrete_000.ogg",
    "footstep_concrete_001.ogg",
    "footstep_concrete_002.ogg",
    "footstep_concrete_003.ogg",
    "footstep_concrete_004.ogg",
};

// Loop-ready versions of the Kenney stoneDrag samples, generated by
// tools/make_drag_loops.py (silence-trimmed, crossfaded seam).
constexpr std::array<const char*, 4> stoneDragFileNames {
    "stoneDragLoop1.ogg",
    "stoneDragLoop2.ogg",
    "stoneDragLoop3.ogg",
    "stoneDragLoop4.ogg",
};

// Short fades hide the click of starting/stopping the drag loop mid-waveform.
constexpr unsigned int dragFadeInMilliseconds = 15;
constexpr unsigned int dragFadeOutMilliseconds = 40;

// Per-level soundtracks (Kenney Music Loops); these files loop cleanly as-is.
constexpr std::array<const char*, 4> musicFileNames {
    "Sad Town.ogg",
    "Sad Descent.ogg",
    "Mission Plausible.ogg",
    "Space Cadet.ogg",
};

constexpr unsigned int musicCrossfadeMilliseconds = 600;

} // namespace

struct AudioSystem::EngineHandle {
    ma_engine engine {};
    bool engineInitialized = false;
    // Fully decoded at load; addresses must stay stable after init, so the
    // vector is sized once and never reallocated.
    std::vector<ma_sound> footstepSounds;
    std::vector<int> loadedFootsteps;
    std::vector<ma_sound> stoneDragSounds;
    std::vector<int> loadedStoneDrags;
    int activeStoneDrag = -1;
    std::vector<ma_sound> musicSounds;
    std::vector<int> loadedMusic;
    int activeMusic = -1;
};

namespace {

void loadSoundSet(
    ma_engine& engine,
    const std::filesystem::path& audioRoot,
    const char* const* fileNames,
    size_t count,
    std::vector<ma_sound>& sounds,
    std::vector<int>& loaded,
    ma_uint32 flags)
{
    // Fully decoded at load; addresses must stay stable after init, so the
    // vector is sized once and never reallocated.
    sounds.resize(count);
    for (size_t i = 0; i < count; ++i) {
        const std::filesystem::path path = audioRoot / fileNames[i];
        const ma_result result = ma_sound_init_from_file(
            &engine,
            path.string().c_str(),
            flags,
            nullptr,
            nullptr,
            &sounds[i]);
        if (result == MA_SUCCESS) {
            loaded.push_back(static_cast<int>(i));
        } else {
            std::cerr << "Audio: failed to load " << path.string() << "\n";
        }
    }
}

} // namespace

AudioSystem::AudioSystem(std::filesystem::path audioRoot)
    : engine_(std::make_unique<EngineHandle>())
    , audioRoot_(std::move(audioRoot))
    , random_(std::random_device {}())
{
    if (ma_engine_init(nullptr, &engine_->engine) != MA_SUCCESS) {
        std::cerr << "Audio disabled: audio engine initialization failed\n";
        return;
    }
    engine_->engineInitialized = true;
    ma_engine_set_volume(&engine_->engine, masterVolume_);

    loadSoundSet(
        engine_->engine, audioRoot_,
        footstepFileNames.data(), footstepFileNames.size(),
        engine_->footstepSounds, engine_->loadedFootsteps,
        MA_SOUND_FLAG_DECODE);
    loadSoundSet(
        engine_->engine, audioRoot_,
        stoneDragFileNames.data(), stoneDragFileNames.size(),
        engine_->stoneDragSounds, engine_->loadedStoneDrags,
        MA_SOUND_FLAG_DECODE);
    // Music is streamed rather than fully decoded; tracks are long and only
    // one plays at a time.
    loadSoundSet(
        engine_->engine, audioRoot_,
        musicFileNames.data(), musicFileNames.size(),
        engine_->musicSounds, engine_->loadedMusic,
        MA_SOUND_FLAG_STREAM);
}

AudioSystem::~AudioSystem()
{
    if (!engine_->engineInitialized) {
        return;
    }
    for (int index : engine_->loadedFootsteps) {
        ma_sound_uninit(&engine_->footstepSounds[static_cast<size_t>(index)]);
    }
    for (int index : engine_->loadedStoneDrags) {
        ma_sound_uninit(&engine_->stoneDragSounds[static_cast<size_t>(index)]);
    }
    for (int index : engine_->loadedMusic) {
        ma_sound_uninit(&engine_->musicSounds[static_cast<size_t>(index)]);
    }
    ma_engine_uninit(&engine_->engine);
}

bool AudioSystem::available() const
{
    return engine_->engineInitialized && !engine_->loadedFootsteps.empty();
}

void AudioSystem::update(float dt, bool playerWalking, bool pushingStone)
{
    const int due = cadence_.update(dt, playerWalking);
    if (due > 0 && available()) {
        // Multiple due steps in one frame collapse into a single sound;
        // stacking identical samples only changes loudness.
        playFootstep();
    }

    if (pushingStone != pushing_) {
        pushing_ = pushingStone;
        if (pushing_) {
            startStoneDrag();
        } else {
            stopStoneDrag();
        }
    }
}

void AudioSystem::playFootstep()
{
    const auto& loaded = engine_->loadedFootsteps;
    int pick = loaded[random_() % loaded.size()];
    if (static_cast<int>(loaded.size()) > 1) {
        while (pick == lastFootstepIndex_) {
            pick = loaded[random_() % loaded.size()];
        }
    }
    lastFootstepIndex_ = pick;

    ma_sound& sound = engine_->footstepSounds[static_cast<size_t>(pick)];
    ma_sound_seek_to_pcm_frame(&sound, 0);
    ma_sound_start(&sound);
}

void AudioSystem::startStoneDrag()
{
    if (!engine_->engineInitialized || engine_->loadedStoneDrags.empty()) {
        return;
    }

    const auto& loaded = engine_->loadedStoneDrags;
    int pick = loaded[random_() % loaded.size()];
    if (static_cast<int>(loaded.size()) > 1) {
        while (pick == lastDragIndex_) {
            pick = loaded[random_() % loaded.size()];
        }
    }
    lastDragIndex_ = pick;
    engine_->activeStoneDrag = pick;

    ma_sound& sound = engine_->stoneDragSounds[static_cast<size_t>(pick)];
    // A prior stop-with-fade leaves a scheduled stop time on the sound; if it
    // is not cleared the restarted sound is silently stopped again right away
    // (see the note on ma_sound_stop_with_fade_* in miniaudio.h).
    ma_sound_reset_stop_time_and_fade(&sound);
    ma_sound_set_looping(&sound, MA_TRUE);
    ma_sound_seek_to_pcm_frame(&sound, 0);
    // The prior stop-with-fade also leaves the volume at zero; fade back in.
    ma_sound_set_fade_in_milliseconds(&sound, 0.0f, 1.0f, dragFadeInMilliseconds);
    ma_sound_start(&sound);
}

void AudioSystem::stopStoneDrag()
{
    if (engine_->activeStoneDrag < 0) {
        return;
    }
    ma_sound& sound =
        engine_->stoneDragSounds[static_cast<size_t>(engine_->activeStoneDrag)];
    ma_sound_stop_with_fade_in_milliseconds(&sound, dragFadeOutMilliseconds);
    engine_->activeStoneDrag = -1;
}

void AudioSystem::playMusic(const char* fileName)
{
    if (!engine_->engineInitialized) {
        return;
    }

    int target = -1;
    if (fileName != nullptr) {
        for (size_t i = 0; i < musicFileNames.size(); ++i) {
            if (std::string_view(musicFileNames[i]) == fileName) {
                target = static_cast<int>(i);
                break;
            }
        }
        const auto& loaded = engine_->loadedMusic;
        if (target >= 0 &&
            std::find(loaded.begin(), loaded.end(), target) == loaded.end()) {
            target = -1;
        }
        if (target < 0) {
            std::cerr << "Audio: music track not loaded: " << fileName << "\n";
        }
    }

    if (target == engine_->activeMusic) {
        return;
    }

    if (engine_->activeMusic >= 0) {
        ma_sound_stop_with_fade_in_milliseconds(
            &engine_->musicSounds[static_cast<size_t>(engine_->activeMusic)],
            musicCrossfadeMilliseconds);
    }
    engine_->activeMusic = target;
    if (target < 0) {
        return;
    }

    ma_sound& sound = engine_->musicSounds[static_cast<size_t>(target)];
    ma_sound_reset_stop_time_and_fade(&sound);
    ma_sound_set_looping(&sound, MA_TRUE);
    ma_sound_seek_to_pcm_frame(&sound, 0);
    ma_sound_set_volume(&sound, musicVolume_);
    ma_sound_set_fade_in_milliseconds(&sound, 0.0f, 1.0f, musicCrossfadeMilliseconds);
    ma_sound_start(&sound);
}

void AudioSystem::setMusicVolume(float volume)
{
    musicVolume_ = std::clamp(volume, 0.0f, 1.0f);
    if (engine_->engineInitialized && engine_->activeMusic >= 0) {
        ma_sound_set_volume(
            &engine_->musicSounds[static_cast<size_t>(engine_->activeMusic)],
            musicVolume_);
    }
}

void AudioSystem::setMasterVolume(float volume)
{
    masterVolume_ = std::clamp(volume, 0.0f, 1.0f);
    if (engine_->engineInitialized) {
        ma_engine_set_volume(&engine_->engine, masterVolume_);
    }
}

void AudioSystem::setFootstepIntervalSeconds(float seconds)
{
    cadence_.intervalSeconds = std::clamp(seconds, 0.05f, 2.0f);
}

} // namespace sokoban
