#pragma once

#include "engine/AssetManifest.hpp"
#include "engine/Math.hpp"
#include "engine/TileTypes.hpp"
#include "engine/render/RenderTypes.hpp"

#include <optional>
#include <string_view>

namespace sokoban {

namespace config {

// Rotator plates are generated by tools/make_rotator_models.py. The tile
// model (manifest `tiles`) is the complete plate; gameplay draws the gear and
// the direction icon separately so the gear can spin while the icon stays put.
inline constexpr std::string_view rotatorGearModelName = "RotatorGear";
inline constexpr std::string_view rotatorClockwiseIconModelName =
    "RotatorIconClockwise";
inline constexpr std::string_view rotatorCounterClockwiseIconModelName =
    "RotatorIconCounterClockwise";
// A rotator is a floor plate like a pressure plate, a little wider so the
// cog teeth read at gameplay zoom.
inline constexpr float rotatorPlateWidthDepth = 0.9f;
inline constexpr float rotatorPlateHeight = 0.1f;
// Plate brightness while its linked plates are not all pressed.
inline constexpr float rotatorIdleBrightness = 0.78f;

} // namespace config

// The gear and icon models, when the manifest declares both. Without them a
// rotator falls back to its single tile model and does not spin.
struct RotatorModelParts {
    RenderModel gear = cubeModel;
    RenderModel icon = cubeModel;
};

[[nodiscard]] inline std::optional<RotatorModelParts> rotatorModelParts(
    const AssetManifest& manifest,
    TileType tile)
{
    const std::optional<RenderModel> gear =
        manifest.findModelIdByName(config::rotatorGearModelName);
    const std::optional<RenderModel> icon = manifest.findModelIdByName(
        tile == TileType::RotatorCounterClockwise
            ? config::rotatorCounterClockwiseIconModelName
            : config::rotatorClockwiseIconModelName);
    if (!gear || !icon) {
        return std::nullopt;
    }
    return RotatorModelParts { .gear = *gear, .icon = *icon };
}

// The plate's footprint and height in the tile's cell.
[[nodiscard]] inline RenderFrameData::Tile rotatorPlateTile(
    GridPosition3 cell,
    Vec4 color,
    RenderModel model)
{
    const float offset = (1.0f - config::rotatorPlateWidthDepth) * 0.5f;
    return {
        .cell = cell,
        .position = {
            static_cast<float>(cell.x) + offset,
            static_cast<float>(cell.y) + offset,
        },
        .size = {
            config::rotatorPlateWidthDepth,
            config::rotatorPlateWidthDepth,
        },
        .color = color,
        .baseElevation = static_cast<float>(cell.z),
        .height = config::rotatorPlateHeight,
        .model = model,
    };
}

// Appends a gameplay rotator: the gear turned by `spinRadians` (positive is
// clockwise seen from above) under a still direction icon. The icon tile is
// not pickable so hover/selection keeps addressing the plate itself.
inline void appendRotatorPlate(
    RenderFrameData& frame,
    GridPosition3 cell,
    TileType tile,
    Vec4 color,
    float spinRadians,
    const AssetManifest& manifest)
{
    const std::optional<RotatorModelParts> parts =
        rotatorModelParts(manifest, tile);
    if (!parts) {
        frame.tiles.push_back(
            rotatorPlateTile(cell, color, manifest.modelForTile(tile)));
        return;
    }
    RenderFrameData::Tile gear = rotatorPlateTile(cell, color, parts->gear);
    gear.modelRotationOffsetRadians = spinRadians;
    frame.tiles.push_back(gear);
    RenderFrameData::Tile icon = rotatorPlateTile(cell, color, parts->icon);
    icon.pickable = false;
    icon.showGrid = false;
    frame.tiles.push_back(icon);
}

} // namespace sokoban
